OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
    SANS:
        - "{{.Hostname}}.alt.{{.Domain}}"
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    CA:
      Hostname: ca # implicitly ca.org1.example.com
    Template:
      Count: 3
      SANS:
        - "{{.Hostname}}.alt.{{.Domain}}"
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.example.com
    CA:
      Hostname: ca # implicitly ca.org2.example.com
    Template:
      Count: 2
      SANS:
        - "{{.Hostname}}.alt.{{.Domain}}"
    Users:
      Count: 1